Mohammad update
sesamiapp/devportal pull request #15
Opened 2024-08-20 20:03 UTC by Mohammad-DH

there is a problem 
i have an image in "docs\sesami-sdk\learn-by-doing.md" line 13
when i uncomment it , i got error 
Error: 0308010C:digital envelope routines::unsupported

2024-09-03 08:52 UTC, MostafaMDZH commented
Hi @Mohammad-DH 
Please instead of puting your name on the PR, specify it's changes.
I don't know this PR is doing what...
Thanks

2025-01-12 18:23 UTC, rmtngh requested changes
Hi @Mohammad-DH 
Thanks for writing this PR,
There a few points that need correction / confirmation:
- The tone of this section is very different from the rest of the docs, to me it sounds more like a personal blog post than an official doc, I'd ask @ekhakbaz to confirm whether this is appropriate according to our brand's voice and tone guidelines.
- There are grammar / spelling / capitalization errors that need to be corrected, please note that it is not feasible to point out every single occurrence in a PR review, so please take another look or run it through something like Grammarly
- There is a mention of a problem in the PR description, but it is not clear if it is resolved yet, you can use checkboxes in description to show / track progress and indicate when an issue is resolved.

Please feel free to ping someone from the team once these are resolved for another review.

2025-01-12 18:28 UTC, Mohammad-DH commented
my apologies sir , sure i will check our other docs to match the tone
i will recheck for grammar / spelling / capitalization errors

unfortunately i didn't fully understand the last one but i will do my best
to look at our other PRs to fix this issue
thanks for the feedback

On Sun, Jan 12, 2025, 9:53 PM rmtngh ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Mohammad-DH <https://github.com/Mohammad-DH>
> Thanks for writing this PR,
> There a few points that need correction / confirmation:
>
>    - The tone of this section is very different from the rest of the
>    docs, to me it sounds more like a personal blog post than an official doc,
>    I'd ask @ekhakbaz <https://github.com/ekhakbaz> to confirm whether
>    this is appropriate according to our brand's voice and tone guidelines.
>    - There are grammar / spelling / capitalization errors that need to be
>    corrected, please note that it is not feasible to point out every single
>    occurrence in a PR review, so please take another look or run it through
>    something like Grammarly
>    - There is a mention of a problem in the PR description, but it is not
>    clear if it is resolved yet, you can use checkboxes in description to show
>    / track progress and indicate when an issue is resolved.
>
> Please feel free to ping someone from the team once these are resolved for
> another review.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sesamiapp/devportal/pull/15#pullrequestreview-2545487464>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATU4VQPDPCD7KSKJYAPMPKD2KKXKFAVCNFSM6AAAAABM2TGS6CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKNBVGQ4DONBWGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-01-20 14:06 UTC, Mohammad-DH commented
hi @rmtngh 
Improved grammar, spelling, and document formatting.
Removed the mentioned issue as it no longer exists and replaced it with a clearer, more detailed description.

About the tone, as I remember, the goal was for it to be like this to make it more friendly
but I made a few changes to improve it and make it more suitable.

2025-01-21 12:13 UTC, rmtngh approved these changes

2025-01-25 21:04 UTC, merged